### PR TITLE
Update description

### PR DESCRIPTION
**Pull request by duboism**
This PR implements some changes in the description of the app.

  - [x] Correct repository URL
  - [x] Add credits
  - [x] Remove duplicated paragraph
  - ~Update list of latest LVK publications~ Not necessary after some checks

### CODE REVIEW

**Comment by rachelmgray** [comment]
Hi Mathieu, the changes look okay to me, the only thing missing is an updated link for the list of LVK publications. [This](https://www.ligo.org/science/outreach.php) might be the best option? (The current list is outdated, and the other list I found was very LSC specific, whereas this at least includes LVK in the title). Might be worth checking in with EPO to see if they have a better alternative, however...

**Comment by duboism** [comment]
@rachelmgray, thanks for reminding me this. The [current page](https://pnp.ligo.org/ppcomm/Papers.html) doesn't seem too outdated (last entry if from July 2024); the [page you pointed out](https://www.ligo.org/science/outreach.php) is targeted toward the general public so I'm not sure if this fits. Maybe it's better to contact the EPO team directly. Perhaps, we can even suggest to create a webpage dedicated to the official Hubble constant measurement.

**Comment by rachelmgray** [comment]
Hi Mathieu, huh, when I looked at that page originally the most recent publication was 2020 (hence the concern). I've now tried clicking the Release Date and it's updated to include everything to 2024. Maybe it was just remembering some weird settings from when I previously visited, though that's a little concerning as I had visited multiple times without an indication that it was a subset of results. Either way probably fine to leave it for now.

**Comment by duboism** [comment]
Hi Rachel,

The web is full of surprises :)

I will switch the PR to ready for review. If I remember correctly, 2 people mentioned in `CODEOWNERS` must approve it.

**Review by NicolaTamanini — APPROVED** [review]

**Comment by duboism** [comment]
OK, the PR is merged. The app is now updated.

**Pull request merged**
