### PR TITLE
Move description in a separate file and update it

### PR DESCRIPTION
**Pull request by duboism**
This PR reads the description of the app from a markdown file instead of putting it in the code. This ease future modifications of the description.

It also updates the content of the file according to recent propositions.

### CODE REVIEW

**Comment by duboism** [comment]
@NicolaTamanini can you review the content of the `Description.md` file ? I export the Google Doc to create so it should be OK (except if I introduced mistakes).

**Comment by duboism** [comment]
I noticed an almost unfathomable difference in display of the section headers between the instance on streamilt and on my computer. I think it's related to minor differences in some CSS so probably not worth spending time on.

**Comment by chrisnorth** [comment]
I suspect that's a streamlit-specific CSS that's inherited. I think we have streamlit specified as v1.
22 in requirements, and there may have been a minor change in styling (I forget what version they're on for deployment). Something to watch, though....

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by duboism** [comment]
@chrisnorth, that's exactly my hypothesis (the HTML is the same so I think it's a difference in CSS ) ! Just to be sure: what do you mean by "something to watch" ? As I said, the differences very small so not worth paying much attention. I guess that you're talking about taking care of not using an outdated version of the `streamlit` package, right ?

**Comment by chrisnorth** [comment]
Yes, that's all I mean - we're probably OK because the versions are fixed, at least for the time being. But it's possible that something more major changes in streamlit at some point, or that the specified version becomes incompatible with the streamlit server

**Review by NicolaTamanini — APPROVED** [review]

**Comment by NicolaTamanini** [comment]
I approved the changes but I believe you need someone else to approve as well.

**Comment by duboism** [comment]
@chrisnorth, would you agree to approve this PR ?

**Review by chrisnorth — APPROVED** [review]

**Comment by duboism** [comment]
Thanks for approving, merging and deploying that !

**Comment by chrisnorth** [comment]
seemed easier to do it all in one go!

**Pull request merged**
